import { Level } from './types';

let id = 0;
const uid = () => `eq-${id++}`;

export const levels: Level[] = [
  {
    id: 0,
    name: 'Getting Started',
    instructions: 'Launch the marble to collect all the stars! Try y = x',
    equations: [
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 2, collected: false },
      { x: 4, y: 4, collected: false },
      { x: 6, y: 6, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 10],
    yRange: [-2, 10],
    marbleStart: null,
  },
  {
    id: 1,
    name: 'Lines & Slopes',
    instructions: 'Use two lines to collect all 4 stars. Add equations!',
    equations: [
      { id: uid(), text: 'y = 0.5x + 1', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 2, collected: false },
      { x: 4, y: 3, collected: false },
      { x: 6, y: 1, collected: false },
      { x: 8, y: -1, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 12],
    yRange: [-4, 8],
    marbleStart: null,
  },
  {
    id: 2,
    name: 'Fix It #1',
    instructions: 'Change the equation below to fix the Marbleslide.',
    equations: [
      { id: uid(), text: 'y = x^2', isInstruction: false, locked: false },
    ],
    stars: [
      { x: -2, y: 6, collected: false },
      { x: 0, y: 2, collected: false },
      { x: 2, y: 6, collected: false },
      { x: 3, y: 11, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-6, 6],
    yRange: [-2, 14],
    marbleStart: null,
  },
  {
    id: 3,
    name: 'Fix It #2',
    instructions: 'Change the row below to fix the Marbleslide.',
    equations: [
      { id: uid(), text: 'y = 2(x-4)^2 + 2 {x<5}', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 4.5, collected: false },
      { x: 4, y: 3, collected: false },
      { x: 7, y: 4.5, collected: false },
      { x: 10, y: 1, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-6, 18],
    yRange: [-4, 12],
    marbleStart: null,
  },
  {
    id: 4,
    name: 'Wave Rider',
    instructions: 'Ride the sine wave! Adjust amplitude and shift.',
    equations: [
      { id: uid(), text: 'y = 2sin(x) + 3', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 1.57, y: 5, collected: false },
      { x: 3.14, y: 3, collected: false },
      { x: 4.71, y: 1, collected: false },
      { x: 6.28, y: 3, collected: false },
      { x: 7.85, y: 5, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 10],
    yRange: [-2, 8],
    marbleStart: null,
  },
  {
    id: 5,
    name: 'Parabola Path',
    instructions: 'Use a parabola in vertex form to collect the stars.',
    equations: [
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 5, collected: false },
      { x: 4, y: 1, collected: false },
      { x: 6, y: 5, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 10],
    yRange: [-2, 10],
    marbleStart: null,
  },
  {
    id: 6,
    name: 'Multi-Curve',
    instructions: 'Use multiple equations to collect all stars scattered around.',
    equations: [
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 1, y: 3, collected: false },
      { x: 3, y: 1, collected: false },
      { x: 5, y: 5, collected: false },
      { x: 7, y: 2, collected: false },
      { x: 9, y: 7, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 12],
    yRange: [-2, 10],
    marbleStart: null,
  },
  {
    id: 7,
    name: 'Gravity Flip',
    instructions: 'Gravity flips after collecting the first star! Use the flip button.',
    equations: [
      { id: uid(), text: 'y = -0.3x^2 + 3x', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 5, collected: false },
      { x: 5, y: 7, collected: false },
      { x: 8, y: 3, collected: false },
      { x: 10, y: 6, collected: false },
    ],
    gravity: 'down',
    canFlipGravity: true,
    gravityWells: [],
    xRange: [-2, 12],
    yRange: [-2, 10],
    marbleStart: null,
  },
  {
    id: 8,
    name: 'Gravity Wells',
    instructions: 'Watch out for gravity wells! They pull the marble off course.',
    equations: [
      { id: uid(), text: 'y = 3', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 3, collected: false },
      { x: 5, y: 5, collected: false },
      { x: 8, y: 3, collected: false },
      { x: 11, y: 1, collected: false },
    ],
    gravity: 'down',
    gravityWells: [
      { x: 4, y: 5, radius: 2, strength: 1 },
      { x: 9, y: 1, radius: 2, strength: -0.8 },
    ],
    canFlipGravity: false,
    xRange: [-2, 14],
    yRange: [-3, 8],
    marbleStart: null,
  },
  {
    id: 9,
    name: 'Zero-G Float',
    instructions: 'No gravity! The marble floats along your curve.',
    equations: [
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 1, y: 2, collected: false },
      { x: 3, y: 4, collected: false },
      { x: 5, y: 1, collected: false },
      { x: 7, y: 5, collected: false },
      { x: 9, y: 3, collected: false },
      { x: 11, y: 6, collected: false },
    ],
    gravity: 'zero',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-2, 14],
    yRange: [-2, 8],
    marbleStart: null,
  },
];
