import { Level } from './types';

export const levels: Level[] = [
  {
    id: 0,
    name: 'Normal',
    description: 'Simple linear, gravity down. Try y = 0.5x + 1',
    stars: [
      { x: 2, y: 2, collected: false },
      { x: 4, y: 3, collected: false },
      { x: 6, y: 4, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    defaultEquation: 'y = 0.5x + 1',
    xRange: [-1, 8],
    yRange: [-1, 6],
  },
  {
    id: 1,
    name: 'Flip It',
    description: 'Quadratic curve, gravity flips after first star',
    stars: [
      { x: 1, y: 2, collected: false },
      { x: 3, y: 2, collected: false },
      { x: 5, y: 2, collected: false },
      { x: 7, y: 6, collected: false },
    ],
    gravity: 'down',
    canFlipGravity: true,
    gravityWells: [],
    defaultEquation: 'y = -0.2x^2 + 2x',
    xRange: [-1, 9],
    yRange: [-2, 8],
  },
  {
    id: 2,
    name: 'Sinusoidal',
    description: 'Ride the wave! Gravity pulls sideways',
    stars: [
      { x: 1.57, y: 1, collected: false },
      { x: 3.14, y: 0, collected: false },
      { x: 4.71, y: -1, collected: false },
      { x: 6.28, y: 0, collected: false },
      { x: 7.85, y: 1, collected: false },
    ],
    gravity: 'right',
    gravityWells: [],
    canFlipGravity: false,
    defaultEquation: 'y = sin(x)',
    xRange: [-1, 10],
    yRange: [-3, 3],
  },
  {
    id: 3,
    name: 'Gravity Well',
    description: 'Gravity wells pull and push! Navigate carefully',
    stars: [
      { x: 2, y: 2, collected: false },
      { x: 4, y: 2, collected: false },
      { x: 6, y: 2, collected: false },
      { x: 8, y: 2, collected: false },
    ],
    gravity: 'down',
    gravityWells: [
      { x: 3, y: 4, radius: 1.5, strength: 0.8 },
      { x: 7, y: 0, radius: 1.5, strength: -0.8 },
    ],
    canFlipGravity: false,
    defaultEquation: 'y = 2',
    xRange: [-1, 10],
    yRange: [-2, 6],
  },
  {
    id: 4,
    name: 'Zero-G',
    description: 'No gravity! The curve is your only guide',
    stars: [
      { x: 1, y: 1.5, collected: false },
      { x: 2.5, y: 0.5, collected: false },
      { x: 4, y: 2, collected: false },
      { x: 5.5, y: -0.5, collected: false },
      { x: 7, y: 1, collected: false },
      { x: 8.5, y: 2.5, collected: false },
    ],
    gravity: 'zero',
    gravityWells: [],
    canFlipGravity: false,
    defaultEquation: 'y = sin(x) + 1',
    xRange: [-1, 10],
    yRange: [-3, 5],
  },
];
