import { Level } from './types';

let id = 0;
const uid = () => `eq-${id++}`;

export const levels: Level[] = [
  {
    id: 0,
    name: 'Let\'s Marbleslide!',
    instructions: '',
    equations: [
      { id: uid(), text: "Here's the goal: Get all the stars. Get to know parabolas.", isInstruction: true, locked: true },
      { id: uid(), text: 'Click "Launch" to see what we mean.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: -2, y: 6, collected: false },
      { x: -3, y: 2, collected: false },
      { x: 2, y: 6, collected: false },
      { x: 3, y: 2, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-6, 10],
    marbleStart: { x: 0, y: 10 },
    answers: ['y = -4/5 x^2 + 46/5'],
  },
  {
    id: 1,
    name: 'Fix It #2',
    instructions: '',
    equations: [
      { id: uid(), text: 'Change the row below to fix the Marbleslide.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 2, y: 4, collected: false },
      { x: 4, y: 2, collected: false },
      { x: 6, y: 4, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-10, 10],
    marbleStart: { x: 0, y: 12 },
    answers: ['y = 1/2(x - 4)^2 + 2 {x < 7}'],
  },
  {
    id: 2,
    name: 'Challenge Slide #5',
    instructions: '',
    equations: [
      { id: uid(), text: 'Get the stars using parabolas.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 3, y: 5, collected: false },
      { x: 1, y: 4, collected: false },
      { x: -3, y: 0, collected: false },
      { x: -1, y: -1, collected: false },
      { x: 1, y: -2, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-6, 10],
    marbleStart: { x: 6, y: 7 },
    answers: ['y = 1/2x + 3 {x > -1}', 'y = -1/2x - 2 {x < 4}'],
  },
  {
    id: 3,
    name: 'Challenge Slide #6',
    instructions: '',
    equations: [
      { id: uid(), text: 'Get the stars. Think big!', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: -5, y: 9, collected: false },
      { x: -1, y: 6.6, collected: false },
      { x: 1, y: 3.6, collected: false },
      { x: 5, y: -6, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-10, 10],
    marbleStart: { x: -4.8, y: 10 },
    answers: ['y = -0.15(x + 5)^2 + 9 {x > -9}'],
  },
  {
    id: 4,
    name: 'Challenge Slide #7',
    instructions: '',
    equations: [
      { id: uid(), text: 'Use parabolas and restrictions. Collect all stars.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 3, y: 9, collected: false },
      { x: 1, y: 8.6, collected: false },
      { x: -1, y: 7.4, collected: false },
      { x: -7, y: -1, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-10, 10],
    marbleStart: { x: 2.8, y: 10 },
    answers: ['y = -0.1(x - 3)^2 + 9 {x < 9}'],
  },
  {
    id: 5,
    name: 'Challenge Slide #1',
    instructions: '',
    equations: [
      { id: uid(), text: 'In the rows below, type as many equations of exponentials as you need to collect all the stars.', isInstruction: true, locked: true },
      { id: uid(), text: 'We have included equations for exponentials that might help you start. (But you can delete them if you don\'t like them.)', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    // Marble starts at x=2.5 (right, just below curve 1 restriction at x=3),
    // slides LEFT on curve 1 past x=-2 (star 1), falls to curve 2 (1.1^x+7),
    // slides left past x=-2 (star 2), falls to curve 3 (0.9^x+4) which goes left,
    // collects star 3 at x=-2, falls to curve 4, crosses star 4 at x=-2.
    // Star positions computed to sit exactly on curves:
    // curve1 at x=-2: -1/2*(-2)+12 = 13
    // curve2 at x=-2: 1.1^(-2)+7 ≈ 7.826
    // curve3 at x=-2: 0.9^(-2)+4 ≈ 5.235
    // curve4 at x=-2: 1.1^(-2)+1 ≈ 1.826
    stars: [
      { x: 4, y: 10, collected: false },
      { x: -4, y: 8, collected: false },
      { x: 4, y: 5, collected: false },
      { x: -4, y: 3, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-2, 18],
    marbleStart: { x: 2.5, y: 14 },
    answers: [
      'y = -1/2x + 12 {x < 3}',
      'y = 1.1^x + 7 {x > -6}',
      'y = 0.9^x + 4 {x < 6}',
      'y = 1.1^x + 1 {x > -6}'
    ],
  },

  {
    id: 6,
    name: 'Fix It #2',
    instructions: '',
    equations: [
      { id: uid(), text: 'Change one number in the row below to fix the Marbleslide.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: -0.785, y: 1.5, collected: false },
      { x: -3.927, y: 1.5, collected: false },
      { x: -7.069, y: 1.5, collected: false },
      { x: -10.210, y: 1.5, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-6, 12],
    marbleStart: { x: 0, y: 8 },
    answers: ['y = 1/2 sin(2x) + 2'],
  },
  {
    id: 7,
    name: 'Absolute Precision',
    instructions: '',
    equations: [
      { id: uid(), text: 'Use absolute value |x| for a sharp bounce.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: -6, y: 2, collected: false },
      { x: -2, y: 4, collected: false },
      { x: 2, y: 4, collected: false },
      { x: 8, y: 1, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-4, 10],
    marbleStart: { x: 0, y: 8 },
    answers: ['y = -0.5|x| + 5'],
  },
  {
    id: 9,
    name: 'Fix It #3',
    instructions: '',
    equations: [
      { id: uid(), text: 'Change one number in the row below to fix the Marbleslide.', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [
      { x: 4, y: -1, collected: false },
      { x: 4, y: -3, collected: false },
      { x: 4, y: -5, collected: false },
      { x: 4, y: -7, collected: false },
    ],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-6, 14],
    yRange: [-8, 6],
    marbleStart: { x: 10, y: 3 },
    answers: ['y = -1 / (x - 4)^2 + 2 {x < 15}'],
  },
  {
    id: 10,
    name: 'Freestyle Sandbox',
    instructions: '',
    equations: [
      { id: uid(), text: '🎨 Build your own level!', isInstruction: true, locked: true },
      { id: uid(), text: 'Use the tools on the right to place Stars and set the Marble start.', isInstruction: true, locked: true },
      { id: uid(), text: 'Then add equations below to collect your stars!', isInstruction: true, locked: true },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
      { id: uid(), text: '', isInstruction: false, locked: false },
    ],
    stars: [],
    gravity: 'down',
    gravityWells: [],
    canFlipGravity: false,
    xRange: [-14, 14],
    yRange: [-10, 10],
    marbleStart: null,
    isFreestyle: true,
  }
];
